version: '3'

env:
  repositories:
    - name: "api"
      github: ember-nexus/api
      location: "api/api"
    - name: "reference-dataset"
      github: ember-nexus/reference-dataset
      location: "api/reference-dataset"
    - name: "web-sdk"
      github: ember-nexus/web-sdk
      location: "frontend/web-sdk"
    - name: "uix"
      github: ember-nexus/uix
      location: "frontend/uix"
    - name: "app-plugin-experimental"
      github: ember-nexus/app-plugin-experimental
      location: "frontend/app-plugin-experimental"
    - name: "app-web"
      github: ember-nexus/app-web
      location: "frontend/app-web"
    - name: "governance"
      github: ember-nexus/governance
      location: "other/governance"
    - name: "python-sdk"
      github: ember-nexus/python-sdk
      location: "python/python-sdk"

tasks:

  default:
    desc: Default help output.
    cmds:
      - task --list

  setup:
    desc: Check required dependencies and clones all Ember Nexus repositories.
    cmds:
      - task: check-docker-is-installed
      - task: check-docker-compose-is-installed
      - task: clone-repositories

  repo-checkout-pull-main:
    desc: Checks out the main branch of every repository, given it does not have uncommited changes.
    silent: true
    cmds:
      - for: { var: repositories }
        cmd: |
          (
            if [ ! -d "{{.ITEM.location}}" ]; then
              echo "Repository {{.ITEM.github}} is not yet cloned to location {{.ITEM.location}}."
              exit 0
            fi
            cd "{{.ITEM.location}}"
            if [[ `git status --porcelain` ]]; then
              echo "Skipped repository {{.ITEM.github}} due to uncommited changes."
            fi
            echo "Repository {{.ITEM.github}} at location {{.ITEM.location}}:"
            if [[ ! `git rev-parse --abbrev-ref HEAD` == "main" ]]; then
              git checkout main
            fi
            git pull
          )
          echo ""

  repo-ls:
    desc: List repositories and their git version.
    silent: true
    cmd: |
      title='"location","GitHub repository","branch","unsaved changes?","branch up to date?"'
      content=$(task repo-ls-raw | jq --slurp -r '.[] | [.location, .github, .branch, .unsavedChanges, .branchUpToDate] | @csv')
      csv=$(echo "$title"; echo "$content")
      echo "$csv" | duckdb -column -c "SELECT * FROM read_csv('/dev/stdin', all_varchar=true)"

  repo-ls-raw:
    silent: true
    cmds:
      - for: { var: repositories }
        cmd: |
          (
            if [ ! -d "{{.ITEM.location}}" ]; then
              echo "{\"location\": \"-\", \"github\": \"{{.ITEM.github}}\", \"branch\": \"-\", \"unsavedChanges\": \"-\", \"branchUpToDate\": \"-\"}"
              exit 0
            fi
            cd "{{.ITEM.location}}"
            branch=$(git rev-parse --abbrev-ref HEAD)
            unsavedChanges="no"
            if [[ `git status --porcelain` ]]; then
              unsavedChanges="yes"
            fi
            git fetch &> /dev/null
            branchUpToDate="no"
            if [[ `git status -uno` == *"Your branch is up to date with"* ]]; then
              branchUpToDate="yes"
            fi
            echo "{\"location\": \"{{.ITEM.location}}\", \"github\": \"{{.ITEM.github}}\", \"branch\": \"${branch}\", \"unsavedChanges\": \"${unsavedChanges}\", \"branchUpToDate\": \"${branchUpToDate}\"}"
          )

  check-docker-is-installed:
    internal: true
    silent: true
    cmd: |
      if [ -x "$(command -v docker)" ]; then
        echo "[OK] docker is installed"
      else
        echo "[ERROR] unable to find docker, please install it."
        echo "        see tutorial here: https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-22-04"
        exit 1
      fi

  check-docker-compose-is-installed:
    internal: true
    silent: true
    cmd: |
      if $(docker compose &>/dev/null) && [ $? -eq 0 ]; then
        echo "[OK] docker compose is installed"
      else
        echo "[ERROR] unable to find docker compose, please install it."
        echo "        see tutorial here: https://docs.docker.com/compose/install/linux/"
        exit 1
      fi

  clone-repositories:
    internal: true
    silent: true
    cmds:
      - for: { var: repositories }
        cmd: |
          if [ -d "{{.ITEM.location}}" ]; then
            echo "Repository {{.ITEM.name}} at location {{.ITEM.location}} is already installed."
            exit 0
          fi
          mkdir -p "./{{.ITEM.location}}"
          echo "[WIP] cloning {{.ITEM.name}}..."
          git clone "git@github.com:{{.ITEM.github}}.git" "./{{.ITEM.location}}"
